version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - go get ./...
  build:
    commands:
      - echo Build started on `date`
      - go build -o gogs
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /home/lesia/gogs/uploadThis.zip
