version: '2'
services:
    gogs:
      build: 
        context: .
      restart: always
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - postgres
      environment:
       - "RUN_CROND=true"
      networks:
       - gogs
      volumes:
       - "gogs-data:/data"
      depends_on: 
       - "postgres"

    postgres:
      image: postgres:9.5
      restart: always
      environment:
       - "POSTGRES_USER=gogs"
       - "POSTGRES_PASSWORD=xxxx888"
       - "POSTGRES_DB=gogs"
       - "POSTGRES_HOST=0.0.0.0:5432"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - gogs
    
networks:
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
