version: '3'
services:
  gogs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - gogs-data:/data/gogs
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: your_gogs_db_password
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  gogs-data:
  mariadb-data:
