# Use the official MariaDB image as the base
FROM mariadb:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=myrootpassword
ENV MYSQL_DATABASE=gogs
ENV MYSQL_USER=gogs
ENV MYSQL_PASSWORD=mygogspassword

# Optionally, you can include additional configurations if needed
# COPY ./my-custom-mariadb-config.cnf /etc/mysql/conf.d/

# Expose the MySQL port (3306) if necessary
EXPOSE 3306
